# -*- coding: utf-8 -*-
"""Lpyrmd_MSSIM_mtdtfn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzK_cPf6sHBQZeerXWEXMUoU2IpNawTk
"""



# dataset

# dataset

import cv2
import os
import torch
import random
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import json

#'''

############################## DATAREAD #########################################################


def create_dataloader(split, SR_rate, augment, batch_size=1, shuffle=False, num_workers=0, pin_memory=False):
    dataset = dataread(split, SR_rate, augment)
    dataloader = DataLoader(dataset, batch_size, shuffle=shuffle, num_workers=num_workers, pin_memory=pin_memory)

    return dataloader

def extract_patches(LR_img, HR_img, Ref_img, patch_size=108, scale=2, stride=108):
    """
    Extracts all patches from LR/HR/Ref images with stride.
    Returns list of (LR_patch, HR_patch, Ref_patch, (Hx,Hy), Hp)
    """
    L_h, L_w = LR_img.shape[:2]
    H_h, H_w = HR_img.shape[:2]

    patches = []
    for y in range(0, L_h - patch_size + 1, stride):
        for x in range(0, L_w - patch_size + 1, stride):
            H_x, H_y = scale * x, scale * y
            H_p = scale * patch_size

            patch_LR = LR_img[y:y + patch_size, x:x + patch_size, :]
            patch_HR = HR_img[H_y:H_y + H_p, H_x:H_x + H_p, :]
            patch_Ref = Ref_img[y:y + patch_size, x:x + patch_size, :]

            patches.append((patch_LR, patch_HR, patch_Ref, (H_x, H_y), H_p))
    return patches

def random_crop(LR_img, HR_img, crop_size, SR_rate):
    # check the shape

    LR_h, LR_w = LR_img.shape[:2]
    HR_h, HR_w = HR_img.shape[:2]
    print('np.round_(LR_h * SR_rate)=', np.round_(LR_h * SR_rate), ', HR_h=', HR_h)
    assert np.round_(LR_h * SR_rate) == HR_h and np.round_(LR_w * SR_rate) == HR_w, 'SR_rate is not correct for LR and HR image'
    # check the crop size
    new_LR_h, new_LR_w = crop_size
    assert new_LR_h <= LR_h and new_LR_w <= LR_w, 'crop_size is too large'

    y1 = random.randint(0, LR_h - new_LR_h)
    x1 = random.randint(0, LR_w - new_LR_w)

    LR_crop = LR_img[y1:y1 + new_LR_h, x1:x1 + new_LR_w, :]
    HR_crop = HR_img[SR_rate * y1:SR_rate * (y1 + new_LR_h), SR_rate * x1:SR_rate * (x1 + new_LR_w), :]

    return LR_crop, HR_crop


def get_id(filename):
    return os.path.splitext(filename)[0].split('_')[0]

class dataread(Dataset):  # for training/testing
    def __init__(self, split, SR_rate, augment=False):

        self.split = split
        self.SR_rate = SR_rate
        self.augment = augment
        self.intensity_list = [1.0, 0.7, 0.5]
        self.crop_size = [32, 32]
        self.patch_size = 108
        self.stride = 108
        self.index_map = []  # for validation/test

        # data split
        if split == 'train':
            #self.LR_dir_l = os.path.join('/workspace/MultiCamDataset/rewite/train/wide_2x/')
            #self.LR_dir_r = os.path.join('/workspace/MultiCamDataset/rewite/train/tele/')
            #self.HR_dir_l = '/workspace/MultiCamDataset/rewite/train/gt/'

            self.LR_dir_l = os.path.join('/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/LR/x2/')
            self.LR_dir_r = os.path.join('/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/Ref/x2/')
            self.HR_dir_l = '/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/HR/'

            self.img_names_l = sorted(os.listdir(self.LR_dir_l))[:100]
            self.img_names_r = sorted(os.listdir(self.LR_dir_r))[:100]
            self.hr_img_names = sorted(os.listdir(self.HR_dir_l))[:100]

            # build dictionaries by id
            self.left_map  = {get_id(f): f for f in self.img_names_l}
            self.right_map = {get_id(f): f for f in self.img_names_r}
            self.hr_map    = {get_id(f): f for f in self.hr_img_names}

            self.index_map = []

            for img_id in self.left_map.keys():
                if img_id not in self.right_map or img_id not in self.hr_map:
                   print(f"[WARN] missing pair for {img_id}")
                   continue

                LR_l_path = os.path.join(self.LR_dir_l, self.left_map[img_id])
                LR_r_path = os.path.join(self.LR_dir_r, self.right_map[img_id])
                HR_path   = os.path.join(self.HR_dir_l, self.hr_map[img_id])

                LR_img = cv2.imread(LR_l_path)
                Ref_img = cv2.imread(LR_r_path)
                HR_img = cv2.imread(HR_path)

                patches = extract_patches(
                          LR_img, HR_img, Ref_img,
                          patch_size=self.patch_size,
                          scale=self.SR_rate,
                          stride=self.stride)

                for patch_idx in range(len(patches)):
                    self.index_map.append((img_id, patch_idx))

        elif split == 'valid':
            #self.LR_dir_l = os.path.join('/workspace/MultiCamDataset/rewite/val/wide_2x/')
            #self.LR_dir_r = os.path.join('/workspace/MultiCamDataset/rewite/val/tele/')
            #self.HR_dir_l = '/workspace/MultiCamDataset/rewite/val/gt/'

            #self.LR_dir_l = os.path.join('/workspace/MultiCamDataset/CUFED/test/wide_down_x1/')
            #self.LR_dir_r = os.path.join('/workspace/MultiCamDataset/CUFED/test/tele_size_crct/')
            #self.HR_dir_l = '/workspace/MultiCamDataset/CUFED/test/wide_size_crct/'
            #self.img_names_l = sorted(os.listdir(self.LR_dir_l))[:30]
            
            self.LR_dir_l = os.path.join('/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/LR/x2/')
            self.LR_dir_r = os.path.join('/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/Ref/x2/')
            self.HR_dir_l = '/workspace/MultiCamDataset/CameraFusion/CameraFusion/train/HR/'
            self.img_names_l = sorted(os.listdir(self.LR_dir_l))[100:]
            
            self.img_names_r = self.img_names_l
            self.hr_img_names = self.img_names_l

            #self.img_names_l = sorted(os.listdir(self.LR_dir_l))
            #self.img_names_r = sorted(os.listdir(self.LR_dir_r))
            #self.hr_img_names = sorted(os.listdir(self.HR_dir_l))

        elif split == 'test':
            #self.LR_dir = os.path.join('/content/drive/MyDrive/ColabNotebooks/Research_works/dataset/DIV2K/DIV2K_valid_LR_bicubic/', 'X'+str(SR_rate))
            self.LR_dir_l = os.path.join('/content/drive/MyDrive/phd/MultiCam_works/MultiCamDataset/MultiCamDataset/rewite/rewite/test/wide_2x')
            self.LR_dir_r = os.path.join('/content/drive/MyDrive/phd/MultiCam_works/MultiCamDataset/MultiCamDataset/rewite/rewite/test/tele')
            self.HR_dir_l = '/content/drive/MyDrive/phd/MultiCam_works/MultiCamDataset/MultiCamDataset/rewite/rewite/test/gt'
            self.img_names_l = sorted(os.listdir(self.LR_dir_l))
            self.img_names_r = sorted(os.listdir(self.LR_dir_r))
            self.hr_img_names = sorted(os.listdir(self.HR_dir_l))

        else:
            raise NameError('split must be "train", "valid" or "test".')



    def __len__(self):
        if self.split == 'train':
           return len(self.index_map)
        else:
          return len(self.img_names_r)



    def __getitem__(self, index):

        if self.split == 'train':

            img_id, patch_idx = self.index_map[index]

            left_name  = self.left_map[img_id]
            right_name = self.right_map[img_id]
            hr_name    = self.hr_map[img_id]

            LR_img_l = cv2.imread(os.path.join(self.LR_dir_l, left_name))
            LR_img_r = cv2.imread(os.path.join(self.LR_dir_r, right_name))
            HR_img_l_full = cv2.imread(os.path.join(self.HR_dir_l, hr_name))

            full_HR_shape = HR_img_l_full.shape[:2]
            patches = extract_patches(LR_img_l, HR_img_l_full, LR_img_r,
                                  patch_size=self.patch_size,
                                  scale=self.SR_rate,
                                  stride=self.stride)

            LR_img_l, HR_img_l, LR_img_r, (H_x, H_y), H_p = patches[patch_idx]

            # Convert to float32 for operations
            LR_img_l = LR_img_l.astype(np.float32) / 255.
            LR_img_r = LR_img_r.astype(np.float32) / 255.
            HR_img_l = HR_img_l.astype(np.float32) / 255.


            if self.augment:
                # random crop
                # geometric transformations
                if random.random() < 0.5: # hflip
                    LR_img_l, LR_img_r = LR_img_l[:, ::-1, :], LR_img_r[:, ::-1, :]
                    HR_img_l = HR_img_l[:, ::-1, :]
                if random.random() < 0.5: # vflip
                    LR_img_l, LR_img_r = LR_img_l[::-1, :, :], LR_img_r[::-1, :, :]
                    HR_img_l = HR_img_l[::-1, :, :]
                if random.random() < 0.5: # rot90
                    LR_img_l, LR_img_r = LR_img_l.transpose(1, 0, 2), LR_img_r.transpose(1, 0, 2)
                    HR_img_l = HR_img_l.transpose(1, 0, 2)

                # intensity scale
                intensity_scale = random.choice(self.intensity_list)
                LR_img_l *= intensity_scale
                LR_img_r *= intensity_scale
                HR_img_l *= intensity_scale

            LR_img_l = np.ascontiguousarray(LR_img_l.transpose(2, 0, 1)) # HWC => CHW
            LR_img_r = np.ascontiguousarray(LR_img_r.transpose(2, 0, 1))
            HR_img_l = np.ascontiguousarray(HR_img_l.transpose(2, 0, 1))

            return torch.from_numpy(LR_img_l), torch.from_numpy(LR_img_r), torch.from_numpy(HR_img_l), left_name,right_name,hr_name


        else:

            LR_img_l = cv2.imread(os.path.join(self.LR_dir_l, self.img_names_l[index])) / 255.  
            LR_img_r = cv2.imread(os.path.join(self.LR_dir_r, self.img_names_r[index])) / 255.
            HR_img_l = cv2.imread(os.path.join(self.HR_dir_l, self.hr_img_names[index])) / 255.

            # Convert
            LR_img_l = np.ascontiguousarray(LR_img_l.transpose(2, 0, 1)) # HWC => CHW
            LR_img_r = np.ascontiguousarray(LR_img_r.transpose(2, 0, 1))
            HR_img_l = np.ascontiguousarray(HR_img_l.transpose(2, 0, 1))

            return torch.from_numpy(LR_img_l), torch.from_numpy(LR_img_r), torch.from_numpy(HR_img_l), self.img_names_l[index],self.img_names_r[index], self.hr_img_names[index]

"""# visualize"""

# visualization

import os
import cv2

import torch
import numpy as np
import matplotlib.pyplot as plt

def save_res(pred_HR_l, img_names_l, folder):
    '''

    Parameters
    ----------
    preds : List
        each pred has a shape of 1x3xHxW. BGR
    img_names : List

    Returns
    -------
    None.

    '''

    for pred_HR_l, img_name_l in zip(pred_HR_l, img_names_l):
        pred_img_l = pred_HR_l[0].detach().cpu().numpy().transpose(1, 2, 0)
        # pred_img_r = pred_HR_r[0].detach().cpu().numpy().transpose(1, 2, 0)
        base_name = os.path.splitext(img_name_l)[0]  # remove any existing extension
        save_path = os.path.join(folder, f"{base_name}.png")
        cv2.imwrite(save_path, np.uint8(pred_img_l * 255))
        #cv2.imwrite(os.path.join(folder, img_name_l), np.uint8(pred_img_l * 255))
        # cv2.imwrite(os.path.join(folder, img_name_r), np.uint8(pred_img_r * 255))
    return


def visualize_training(save_dir, epoch_start):
    txt_res = os.path.join(save_dir, f"result_epoch_{epoch_start}.txt")
    with open(txt_res, 'r') as f:
        info = f.readlines()
    epoch, lr, train_loss, valid_loss, psnr = [], [], [], [], []

    for line in info[:-1]:
        line = line.strip().split('|')
        epoch.append(int(line[0].split(':')[1]))
        lr.append(float(line[1].split(':')[1]))
        train_loss.append(float(line[2].split(':')[1]))
        valid_loss.append(float(line[3].split(':')[1]))
        psnr.append(float(line[4].split(':')[1]))

    fig = plt.figure(figsize=(16, 8), dpi=400)
    ax1 = fig.add_subplot(221)
    ax2 = fig.add_subplot(222)
    ax3 = fig.add_subplot(223)
    ax4 = fig.add_subplot(224)
    ax1.title.set_text('Training loss')
    ax2.title.set_text('Validation loss')
    ax3.title.set_text('PSNR (validation)')
    ax4.title.set_text('learning rate')
    ax1.plot(epoch, train_loss)
    ax2.plot(epoch, valid_loss)
    ax3.plot(epoch, psnr)
    ax4.plot(epoch, lr)
    plt.savefig(os.path.join(save_dir, 'results.png'), dpi=200)
    return

# metric


import torch

def cal_psnr(x, y):
    '''
    Parameters
    ----------
    x, y are two tensors has the same shape (1, C, H, W)

    Returns
    -------
    score : PSNR.
    '''

    mse = torch.mean((x - y) ** 2, dim=[1, 2, 3])
    score = - 10 * torch.log10(mse)
    return score

#! pip install pytorch_msssim

# loss

import torch
from torch import nn
from pytorch_msssim import MS_SSIM




class L1Loss(object):
    def __call__(self, input, target):
        return torch.abs(input - target).mean()

class MS_SSIMloss(torch.nn.Module):
    def __init__(self, data_range=1.0, channel=3):
        super().__init__()
        self.ms_ssim = MS_SSIM(
            data_range=data_range,
            size_average=True,
            channel=channel
        )

    def forward(self, X, Y):
        # returns 1 - MS-SSIM
        return 1.0 - self.ms_ssim(X, Y)


class CharbonnierLoss(nn.Module):

    def __init__(self, eps=0.01):
        super(CharbonnierLoss, self).__init__()
        self.eps = eps

    def forward(self, pred, gt):
        # print(len(pred),'&', len(gt))
        loss = torch.sqrt((pred - gt)**2 + self.eps).mean()

        return loss.mean()

"""# MODEL"""

########################
# Teager Energy Layer
########################

class TeagerEnergyLayer(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self._norm = nn.InstanceNorm2d(in_channels, affine=True)

    def forward(self, x):
        # Pad for boundary conditions
        x_pad = torch.cat((x[:, :, :1], x, x[:, :, -1:]), dim=2)
        x_pad = torch.cat((x_pad[:, :, :, :1], x_pad, x_pad[:, :, :, -1:]), dim=3)

        teo_output = (
            x_pad[:, :, 1:-1, 1:-1] ** 2
            - x_pad[:, :, :-2, 1:-1] * x_pad[:, :, 2:, 1:-1]
            - x_pad[:, :, 1:-1, :-2] * x_pad[:, :, 1:-1, 2:]
        )
        teo_output = self._norm(teo_output)
        return teo_output

########################
# Quantized Deform Conv
########################

#class QuantDeformConv2d(nn.Module):
#    def __init__(self, in_channels, out_channels, kernel_size=3, bias=True):
#        super().__init__()
#        self.kernel_size = kernel_size
#        self.in_channels = in_channels
#        self.out_channels = out_channels
#        self.N = kernel_size * kernel_size
#
#        self.weight = nn.Parameter(torch.randn(out_channels, in_channels, kernel_size, kernel_size))
#        self.bias = nn.Parameter(torch.zeros(out_channels)) if bias else None
#
#    def forward(self, x, offset, mask=None):
#        B, C, H, W = x.shape
#        x = x.contiguous()
#
#        offset = (offset.view(B, self.N, 2, H, W).permute(0, 3, 4, 1, 2).contiguous())  # [B,H,W,N,2]
#        if mask is not None:
#            mask = (mask.view(B, self.N, H, W).permute(0, 2, 3, 1).unsqueeze(-1).contiguous())
#
#        # Base grid
#        grid_y, grid_x = torch.meshgrid(
#            torch.arange(H, dtype=offset.dtype, device=x.device),
#            torch.arange(W, dtype=offset.dtype, device=x.device),
#            indexing="ij"
#        )
#        base_grid = torch.stack((grid_x, grid_y), dim=-1).unsqueeze(0).unsqueeze(3) # (1,H,W,1,2)
#
#        sampling_locations = base_grid + offset
#        sampling_locations = sampling_locations / torch.tensor(
#            [W - 1, H - 1], device=x.device
#        ) * 2 - 1
#        sampling_locations = (sampling_locations.reshape(B, H, W * self.N, 2).contiguous())
#        sampling_locations = sampling_locations.clamp(-1 + 1e-4, 1 - 1e-4)
#
#        x_sampled = F.grid_sample(x, sampling_locations, mode="bilinear", padding_mode="zeros", align_corners=True)
#        x_sampled = (x_sampled.view(B, C, H, W, self.N).permute(0, 2, 3, 4, 1).contiguous())
#
#        if mask is not None:
#            x_sampled = x_sampled * mask
#
#        x_sampled = (x_sampled.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous())
#        weight = self.weight.view(self.out_channels, -1, 1, 1)
#        return F.conv2d(x_sampled, weight, bias=self.bias)

import torch
import torch.nn as nn
import torch.nn.functional as F


# class QuantDeformConv2d(nn.Module):
#     def __init__(self, in_channels, out_channels, kernel_size=3, bias=True):
#         super().__init__()

#         self.kernel_size = kernel_size
#         self.in_channels = in_channels
#         self.out_channels = out_channels
#         self.N = kernel_size * kernel_size

#         self.weight = nn.Parameter(
#             torch.randn(out_channels, in_channels, kernel_size, kernel_size)
#         )
#         self.bias = nn.Parameter(torch.zeros(out_channels)) if bias else None

#     def forward(self, x, offset, mask=None):
#         """
#         x      : (B, C, H, W)
#         offset : (B, 2*N, H, W)
#         mask   : (B, N, H, W) or None
#         """

#         B, C, H, W = x.shape
#         x = x.contiguous()

#         # -------- reshape offsets --------
#         offset = offset.view(B, self.N, 2, H, W) \
#                        .permute(0, 3, 4, 1, 2) \
#                        .contiguous()           # (B,H,W,N,2)

#         if mask is not None:
#             mask = mask.view(B, self.N, H, W) \
#                        .permute(0, 2, 3, 1) \
#                        .unsqueeze(-1) \
#                        .contiguous()          # (B,H,W,N,1)

#         # -------- base grid --------
#         grid_y, grid_x = torch.meshgrid(
#             torch.arange(H, device=x.device, dtype=x.dtype),
#             torch.arange(W, device=x.device, dtype=x.dtype),
#             indexing="ij"
#         )
#         base_grid = torch.stack((grid_x, grid_y), dim=-1) \
#                         .unsqueeze(0).unsqueeze(3)        # (1,H,W,1,2)

#         # -------- normalized sampling grid --------
#         sampling_locations = base_grid + offset
#         sampling_locations[..., 0] = sampling_locations[..., 0] / (W - 1) * 2 - 1
#         sampling_locations[..., 1] = sampling_locations[..., 1] / (H - 1) * 2 - 1
#         sampling_locations = sampling_locations.clamp(-1 + 1e-4, 1 - 1e-4)

#         # -------- grouped grid sampling --------
#         sampled = []

#         # Disable cuDNN ONLY here (safe + fast)
#         with torch.backends.cudnn.flags(enabled=False):
#             for n in range(self.N):
#                 grid_n = sampling_locations[..., n, :].contiguous()  # (B,H,W,2)
#                 sampled_n = F.grid_sample(
#                     x,
#                     grid_n,
#                     mode="bilinear",
#                     padding_mode="zeros",
#                     align_corners=True
#                 )  # (B,C,H,W)
#                 sampled.append(sampled_n)

#         # Stack kernel samples
#         x_sampled = torch.stack(sampled, dim=-1)  # (B,C,H,W,N)

#         # -------- apply modulation mask --------
#         if mask is not None:
#             x_sampled = x_sampled * mask.permute(0, 4, 1, 2, 3)

#         # -------- reshape for 1x1 convolution --------
#         x_sampled = x_sampled.permute(0, 2, 3, 4, 1) \
#                              .reshape(B, H, W, -1) \
#                              .permute(0, 3, 1, 2) \
#                              .contiguous()

#         weight = self.weight.view(self.out_channels, -1, 1, 1)
#         out = F.conv2d(x_sampled, weight, bias=self.bias)

#         return out

class QuantDeformConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, bias=True):
        super().__init__()

        self.kernel_size = kernel_size
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.N = kernel_size * kernel_size

        self.weight = nn.Parameter(
            torch.randn(out_channels, in_channels, kernel_size, kernel_size)
        )

        self.bias = nn.Parameter(torch.zeros(out_channels)) if bias else None


    def forward(self, x, offset, mask=None):

        B, C, H, W = x.shape

        # reshape offsets
        offset = offset.view(B, self.N, 2, H, W).permute(0,3,4,1,2)

        if mask is not None:
            mask = mask.view(B,self.N,H,W).permute(0,2,3,1)


        # base grid
        grid_y, grid_x = torch.meshgrid(
            torch.arange(H, device=x.device, dtype=x.dtype),
            torch.arange(W, device=x.device, dtype=x.dtype),
            indexing="ij"
        )

        base_grid = torch.stack((grid_x,grid_y),dim=-1)
        base_grid = base_grid.unsqueeze(0).unsqueeze(3)


        sampling_locations = base_grid + offset

        sampling_locations[...,0] = sampling_locations[...,0]/(W-1)*2-1
        sampling_locations[...,1] = sampling_locations[...,1]/(H-1)*2-1

        sampling_locations = sampling_locations.clamp(-1+1e-4,1-1e-4)


        # Allocate final tensor directly
        x_sampled = torch.empty(
            B,
            C*self.N,
            H,
            W,
            device=x.device,
            dtype=x.dtype
        )


        # grid sample per kernel position
        with torch.backends.cudnn.flags(enabled=False):

            for n in range(self.N):

                grid_n = sampling_locations[...,n,:]

                sampled_n = F.grid_sample(
                    x,
                    grid_n,
                    mode="bilinear",
                    padding_mode="zeros",
                    align_corners=True
                )

                if mask is not None:
                    sampled_n = sampled_n * mask[...,n].unsqueeze(1)


                x_sampled[:, n*C:(n+1)*C,:,:] = sampled_n


        weight = self.weight.view(self.out_channels,-1,1,1)

        out = F.conv2d(x_sampled,weight,bias=self.bias)

        return out



########################
# Deform Align Block
########################

class DeformAlignBlock(nn.Module):
    def __init__(self, in_channels, kernel_size=3, modulation=False):
        super().__init__()
        self.kernel_size = kernel_size
        self.N = kernel_size * kernel_size
        self.modulation = modulation

        self.offset_conv = nn.Conv2d(in_channels * 2, 2 * self.N, kernel_size=3, padding=1)
        nn.init.constant_(self.offset_conv.weight, 0)
        nn.init.constant_(self.offset_conv.bias, 0)

        if modulation:
            self.mask_conv = nn.Conv2d(in_channels * 2, self.N, kernel_size=3, padding=1)
            nn.init.constant_(self.mask_conv.weight, 0)
            nn.init.constant_(self.mask_conv.bias, 0)

        self.deform_conv = QuantDeformConv2d(in_channels, in_channels, kernel_size)
        self.post = nn.Sequential(
            nn.Conv2d(in_channels, in_channels, kernel_size=3, padding=1),
            nn.GELU()
        )

        self.teager_layer = TeagerEnergyLayer(in_channels)

    def forward(self, lr_feat, ref_feat, teager):
        B, C, H_lr, W_lr = lr_feat.shape
        B, C, H_ref, W_ref = ref_feat.shape

        if teager == True:
                # Apply Teager Energy Operator
                teager_ref_feat = self.teager_layer(ref_feat)
                teager_ref_up = F.interpolate(teager_ref_feat, size=(H_lr, W_lr), mode="bilinear", align_corners=False)
        else:
                teager_ref_up = F.interpolate(ref_feat, size=(H_lr, W_lr), mode="bilinear", align_corners=False)

        fused = torch.cat([teager_ref_up, lr_feat], dim=1)
        offset = torch.tanh(self.offset_conv(fused)) * 3.0

        if self.modulation:
            mask = torch.sigmoid(self.mask_conv(fused))
            aligned = self.deform_conv(lr_feat, offset, mask)
        else:
            aligned = self.deform_conv(lr_feat, offset)

        out = aligned + lr_feat
        out = self.post(out)
        return out


# This part code based on EFDN (https://github.com/icandle/EFDN.git) model modified for asymmetric dual camera and Replaced with MT Loss


import torch
import torch.nn as nn
import math
from torch.quantization import QuantStub, DeQuantStub
from torchsummary import summary


# -*- coding: utf-8 -*-
import torch
import torch.nn as nn
import torch.nn.functional as F


class ESA(nn.Module):
    def __init__(self, n_feats, conv):
        super(ESA, self).__init__()
        f = n_feats // 4
        self.conv1 = conv(n_feats, f, kernel_size=1)
        self.conv_f = conv(f, f, kernel_size=1)
        self.conv_max = conv(f, f, kernel_size=3, padding=1)
        self.conv2 = conv(f, f, kernel_size=3, stride=2, padding=0)
        self.conv3 = conv(f, f, kernel_size=3, padding=1)
        self.conv3_ = conv(f, f, kernel_size=3, padding=1)
        self.conv4 = conv(f, n_feats, kernel_size=1)
        self.sigmoid = nn.Sigmoid()
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        c1_ = (self.conv1(x))
        c1 = self.conv2(c1_)
        v_max = F.max_pool2d(c1, kernel_size=7, stride=3)
        v_range = self.relu(self.conv_max(v_max))
        c3 = self.relu(self.conv3(v_range))
        c3 = self.conv3_(c3)
        c3 = F.interpolate(c3, (x.size(2), x.size(3)), mode='bilinear', align_corners=False)
        cf = self.conv_f(c1_)
        c4 = self.conv4(c3+cf)
        m = self.sigmoid(c4)

        return x * m


class conv(nn.Module):
    def __init__(self, n_feats):
        super(conv, self).__init__()
        self.conv1x1 = nn.Conv2d(n_feats, n_feats, 1, 1, 0)
        self.act = nn.PReLU(num_parameters=n_feats)
    def forward(self, x):
        return self.act(self.conv1x1(x))


class Cell(nn.Module):
    def __init__(self, n_feats, deploy , dynamic = True,  L= None, with_13=False):
        super(Cell, self).__init__()

        self.conv1 = conv(n_feats)#nn.Conv2d(n_feats, n_feats, 1, 1, 0)
        # if deploy:
        #     self.conv2 = MFDB_deploy(n_feats,n_feats)
        #     self.conv3 = MFDB_deploy(n_feats,n_feats)
        # else:
        #     self.conv2 = MFDB(n_feats,n_feats)
        #     self.conv3 = MFDB(n_feats,n_feats)

        self.conv2 = MFDB(n_feats,n_feats, deploy)
        self.conv3 = MFDB(n_feats,n_feats, deploy)


        self.fuse = nn.Conv2d(n_feats*2, n_feats, 1, 1, 0)

        self.att = ESA(n_feats, nn.Conv2d) #MAB(n_feats)# ENLCA(n_feats)  #CoordAtt(n_feats,n_feats,10)#

        self.branch = nn.ModuleList([nn.Conv2d(n_feats, n_feats//2, 1, 1, 0) for _ in range(4)])

    def forward(self, x):
        out1 = self.conv1(x)
        out2 = self.conv2(out1)
        out3 = self.conv3(out2)

        # fuse [x, out1, out2, out3]
        out = self.fuse(torch.cat([self.branch[0](x), self.branch[1](out1), self.branch[2](out2), self.branch[3](out3)], dim=1))
        out = self.att(out)
        out += x

        return out


class MTDTFN(nn.Module):
    def __init__(self, scale, deploy, in_channels=3, n_feats=48, out_channels=3):
        super(MTDTFN, self).__init__()
        self.upsample = scale
        
        self.head = nn.Conv2d(in_channels, n_feats, 3, 1, 1)
        # body cells
        self.cells = nn.ModuleList([Cell(n_feats, deploy) for _ in range(4)])

        # fusion
        self.local_fuse = nn.ModuleList([nn.Conv2d(n_feats*2, n_feats, 1, 1, 0) for _ in range(3)])

        self.deformAlignBlock = DeformAlignBlock(n_feats)

        self.tail = nn.Sequential(
           nn.Conv2d(n_feats, out_channels*(scale**2), 3, 1, 1),
           nn.PixelShuffle(scale))

#        if deploy == False:
#          self.wrap_SR2tele = DeformAlignBlock(3)
#        self.tail = nn.Sequential(
#            nn.Conv2d(n_feats, out_channels*(scale**2), 3, 1, 1),
#            nn.PixelShuffle(scale)
#        )

    def forward(self, x, y):
        # head
        out0_x = self.head(x)
        out0_y = self.head(y)

        # body cells
        out1 = self.cells[0](out0_x)
        out2 = self.cells[1](out1)
        out2_fuse = self.local_fuse[0](torch.cat([out1, out2], dim=1))
        out3 = self.cells[2](out2_fuse)
        out3_fuse = self.local_fuse[1](torch.cat([out2, out3], dim=1))
        out4 = self.cells[3](out3_fuse)
        out4_fuse = self.local_fuse[2](torch.cat([out2, out4], dim=1))

        out_fuse = self.deformAlignBlock (out4_fuse, out0_y, teager=True)
        out = out0_x + out_fuse

        # tail
        out = self.tail(out)
        
        x_up = F.interpolate(x, scale_factor= self.upsample, mode='bilinear', align_corners=False)
        
        out = x_up + out 
        
        out = out.clamp(0,1)
        return out

#        if train == True:
#           b,c,new_H, new_W = y.shape
#           wrapped_SR = TF.center_crop(out, (new_H, new_W))
#           wrapped_SR = self.wrap_SR2tele(y,wrapped_SR, teager=False)
#           return out, wrapped_SR
#
#        else:
#           return out

    def switch_to_deploy(self):
        """
        Recursively convert all deployable blocks (like EDBB) into deploy mode.
        """
        for m in self.modules():
            if hasattr(m, "switch_to_deploy") and m is not self:
                m.switch_to_deploy()


# -------------------------------------------------
#This part code based on DBB(https://github.com/DingXiaoH/DiverseBranchBlock) and ECB(https://github.com/xindongzhang/ECBSR)
# def multiscale(kernel, target_kernel_size):
#     H_pixels_to_pad = (target_kernel_size - kernel.size(2)) // 2
#     W_pixels_to_pad = (target_kernel_size - kernel.size(3)) // 2
#     return F.pad(kernel, [H_pixels_to_pad, H_pixels_to_pad, W_pixels_to_pad, W_pixels_to_pad])

def multiscale(kernel, target_kernel_size):
    """Pad kernel to target size (left, right, top, bottom)."""
    H_pad = (target_kernel_size - kernel.size(2)) // 2
    W_pad = (target_kernel_size - kernel.size(3)) // 2
    return F.pad(kernel, [W_pad, W_pad, H_pad, H_pad])


# =========================================================
# Sequential 1x1 + Special 3x3 Convs
# =========================================================
class SeqConv3x3(nn.Module):
    def __init__(self, seq_type, inp_planes, out_planes, depth_multiplier):
        super(SeqConv3x3, self).__init__()

        self.type = seq_type
        self.inp_planes = inp_planes
        self.out_planes = out_planes

        # -------------------------------
        # 1x1 + 3x3 Standard Reparam Path
        # -------------------------------

        if self.type == 'conv1x1-conv3x3':
            self.mid_planes = int(out_planes * depth_multiplier)
            conv0 = torch.nn.Conv2d(self.inp_planes, self.mid_planes, kernel_size=1, padding=0)
            self.k0 = conv0.weight
            self.b0 = conv0.bias

            conv1 = torch.nn.Conv2d(self.mid_planes, self.out_planes, kernel_size=3)
            self.k1 = conv1.weight
            self.b1 = conv1.bias

        # -------------------------------
        # Teager + Sobel X
        # -------------------------------
        elif self.type == 'conv1x1TeagerSobelx':
            conv0 = torch.nn.Conv2d(self.inp_planes, self.out_planes, kernel_size=1, padding=0)
            self.k0 = conv0.weight
            self.b0 = conv0.bias

            # init scale & bias
            scale = torch.randn(size=(self.out_planes, 1, 1, 1)) * 1e-3
            self.scale = nn.Parameter(scale)
            bias = torch.randn(self.out_planes) * 1e-3
            bias = torch.reshape(bias, (self.out_planes,))
            self.bias = nn.Parameter(bias)
            # init mask
            self.mask = torch.zeros((self.out_planes, 1, 3, 3), dtype=torch.float32)
            for i in range(self.out_planes):
                self.mask[i, 0, 1, 1] = 1.0      # centre excitation to mimic All pass Filter
                self.mask[i, 0, 0, 1] = -0.5
                self.mask[i, 0, 2, 1] = -0.5

                # SobelX horizontal gradient (stronger weights)
                self.mask[i, 0, 0, 0] = -1.0       # top-left
                self.mask[i, 0, 0, 2] = 1.0        # top-right
                self.mask[i, 0, 1, 0] = -2.0       # mid-left
                self.mask[i, 0, 1, 2] = 2.0        # mid-right
                self.mask[i, 0, 2, 0] = -1.0       # bot-left
                self.mask[i, 0, 2, 2] = 1.0        # bot-right (+Teager)

            self.mask = nn.Parameter(data=self.mask, requires_grad=False)

        # -------------------------------
        # Teager + Sobel Y
        # -------------------------------
        elif self.type == 'conv1x1TeagerSobely':
            conv0 = torch.nn.Conv2d(self.inp_planes, self.out_planes, kernel_size=1, padding=0)
            self.k0 = conv0.weight
            self.b0 = conv0.bias

            # init scale & bias
            scale = torch.randn(size=(self.out_planes, 1, 1, 1)) * 1e-3
            self.scale = nn.Parameter(torch.FloatTensor(scale))

            bias = torch.randn(self.out_planes) * 1e-3
            bias = torch.reshape(bias, (self.out_planes,))
            self.bias = nn.Parameter(torch.FloatTensor(bias))
            # init mask
            self.mask = torch.zeros((self.out_planes, 1, 3, 3), dtype=torch.float32)
            for i in range(self.out_planes):

                self.mask[i, 0, 1, 1] = 1.0      # centre excitation to mimic All pass Filter
                self.mask[i, 0, 1, 0] = -0.5
                self.mask[i, 0, 1, 2] = -0.5
                
                # SobelY horizontal gradient (stronger weights)
                self.mask[i, 0, 0, 0] = 1.0
                self.mask[i, 0, 0, 1] = 2.0
                self.mask[i, 0, 0, 2] = 1.0
                self.mask[i, 0, 2, 0] = -1.0
                self.mask[i, 0, 2, 1] = -2.0
                self.mask[i, 0, 2, 2] = -1.0

            self.mask = nn.Parameter(data=self.mask, requires_grad=False)

        # -------------------------------
        # Laplacian
        # -------------------------------
        elif self.type == 'conv1x1-laplacian':
            conv0 = torch.nn.Conv2d(self.inp_planes, self.out_planes, kernel_size=1, padding=0)
            self.k0 = conv0.weight
            self.b0 = conv0.bias

            # init scale & bias
            scale = torch.randn(size=(self.out_planes, 1, 1, 1)) * 1e-3
            self.scale = nn.Parameter(torch.FloatTensor(scale))

            bias = torch.randn(self.out_planes) * 1e-3
            bias = torch.reshape(bias, (self.out_planes,))
            self.bias = nn.Parameter(torch.FloatTensor(bias))
            # init mask
            self.mask = torch.zeros((self.out_planes, 1, 3, 3), dtype=torch.float32)
            for i in range(self.out_planes):
                self.mask[i, 0, 0, 1] = 1.0
                self.mask[i, 0, 1, 0] = 1.0
                self.mask[i, 0, 1, 2] = 1.0
                self.mask[i, 0, 2, 1] = 1.0
                self.mask[i, 0, 1, 1] = -4.0
            self.mask = nn.Parameter(data=self.mask, requires_grad=False)
        else:
            raise ValueError('the type of seqconv is not supported!')

    def forward(self, x):
        if self.type == 'conv1x1-conv3x3':
            # conv-1x1
            y0 = F.conv2d(input=x, weight=self.k0, bias=self.b0, stride=1)

            # explicitly padding with bias
            y0 = F.pad(y0, (1, 1, 1, 1), 'constant', 0)
            b0_pad = self.b0.view(1, -1, 1, 1)

            y0[:, :, 0:1, :] = b0_pad
            y0[:, :, -1:, :] = b0_pad
            y0[:, :, :, 0:1] = b0_pad
            y0[:, :, :, -1:] = b0_pad
            # conv-3x3
            y1 = F.conv2d(input=y0, weight=self.k1, bias=self.b1, stride=1)
        else:
            y0 = F.conv2d(input=x, weight=self.k0, bias=self.b0, stride=1)
            # explicitly padding with bias
            y0 = F.pad(y0, (1, 1, 1, 1), 'constant', 0)
            b0_pad = self.b0.view(1, -1, 1, 1)
            y0[:, :, 0:1, :] = b0_pad
            y0[:, :, -1:, :] = b0_pad
            y0[:, :, :, 0:1] = b0_pad
            y0[:, :, :, -1:] = b0_pad
            # conv-3x3
            y1 = F.conv2d(input=y0, weight=self.scale * self.mask, bias=self.bias, stride=1, groups=self.out_planes)
        return y1

    def rep_params(self):
        device = self.k0.get_device()
        if device < 0:
            device = None

        if self.type == 'conv1x1-conv3x3':
            # re-param conv kernel
            RK = F.conv2d(input=self.k1, weight=self.k0.permute(1, 0, 2, 3))
            # re-param conv bias
            RB = torch.ones(1, self.mid_planes, 3, 3, device=device) * self.b0.view(1, -1, 1, 1)
            RB = F.conv2d(input=RB, weight=self.k1).view(-1,) + self.b1
        else:
            tmp = self.scale * self.mask
            k1 = torch.zeros((self.out_planes, self.out_planes, 3, 3), device=device)
            for i in range(self.out_planes):
                k1[i, i, :, :] = tmp[i, 0, :, :]
            b1 = self.bias
            # re-param conv kernel
            RK = F.conv2d(input=k1, weight=self.k0.permute(1, 0, 2, 3))
            # re-param conv bias
            RB = torch.ones(1, self.out_planes, 3, 3, device=device) * self.b0.view(1, -1, 1, 1)
            RB = F.conv2d(input=RB, weight=k1).view(-1,) + b1
        return RK, RB

class MFDB(nn.Module):
    def __init__(self, inp_planes, out_planes, deploy, depth_multiplier=None, act_type='prelu', with_idt = False, with_13=False, gv=False):
        super(MFDB, self).__init__()

        self.deploy = deploy
        self.act_type = act_type

        self.inp_planes = inp_planes
        self.out_planes = out_planes

        self.gv = gv

        if depth_multiplier is None:
            self.depth_multiplier = 1.0
        else:
            self.depth_multiplier = depth_multiplier   # For mobilenet, it is better to have 2X internal channels

        if deploy:
            self.rep_conv = nn.Conv2d(in_channels=inp_planes, out_channels=out_planes, kernel_size=3, stride=1,
                                      padding=1, bias=True)
        else:
            self.with_13 = with_13
            if with_idt and (self.inp_planes == self.out_planes):
                self.with_idt = True
            else:
                self.with_idt = False

            self.rep_conv = nn.Conv2d(self.inp_planes, self.out_planes, kernel_size=3, padding=1)
            self.conv1x1 = nn.Conv2d(self.inp_planes, self.out_planes, kernel_size=1, padding=0)
            self.conv1x1_3x3 = SeqConv3x3('conv1x1-conv3x3', self.inp_planes, self.out_planes, self.depth_multiplier)
            self.conv1x1_teo_sbx = SeqConv3x3('conv1x1TeagerSobelx', self.inp_planes, self.out_planes, -1)
            self.conv1x1_teo_sby = SeqConv3x3('conv1x1TeagerSobely', self.inp_planes, self.out_planes, -1)
            self.conv1x1_lpl = SeqConv3x3('conv1x1-laplacian', self.inp_planes, self.out_planes, -1)

        if self.act_type == 'prelu':
            self.act = nn.PReLU(num_parameters=self.out_planes)
        elif self.act_type == 'relu':
            self.act = nn.ReLU(inplace=True)
        elif self.act_type == 'rrelu':
            self.act = nn.RReLU(lower=-0.05, upper=0.05)
        elif self.act_type == 'softplus':
            self.act = nn.Softplus()
        elif self.act_type == 'linear':
            pass
        else:
            raise ValueError('The type of activation if not support!')
    
    # Laplacian Pyramid

    def lap_pyr(self, x):
        """
        Memory-efficient Laplacian pyramid fusion.
        Math-equivalent to the original implementation.
        """

        # Level 1 (full resolution)
        out = self.conv1x1_lpl(x)

        # Level 2
        x2 = F.avg_pool2d(x, kernel_size=2, stride=2)
        L2 = self.conv1x1_lpl(x2)
        L2 = F.interpolate(L2, size=x.shape[-2:], mode='bilinear', align_corners=False)
        out = out + 0.25 * L2

        # Free early
        del x2, L2

        # Level 3
        x3 = F.avg_pool2d(x, kernel_size=4, stride=4)
        L3 = self.conv1x1_lpl(x3)
        L3 = F.interpolate(L3, size=x.shape[-2:], mode='bilinear', align_corners=False)
        out = out + 0.0625 * L3

        del x3, L3

        return out

    # -------------------------------------------------------------
    # Forward
    # -------------------------------------------------------------

    def forward(self, x):
        if self.deploy:
            y = self.rep_conv(x)
        elif self.gv:
            y = self.rep_conv(x)     + \
                self.conv1x1_teo_sbx(x) + \
                self.conv1x1_teo_sby(x) + \
                self.lap_pyr(x) + x
        else:
            y = self.rep_conv(x)     + \
                self.conv1x1(x)     + \
                self.conv1x1_teo_sbx(x) + \
                self.conv1x1_teo_sby(x) + \
                self.lap_pyr(x)

            if self.with_idt:
                y += x
            if self.with_13:
                y += self.conv1x1_3x3(x)

        if self.act_type != 'linear':
            y = self.act(y)
        return y

    def switch_to_gv(self):
        if self.gv:
            return
        self.gv = True

        K0, B0 = self.rep_conv.weight, self.rep_conv.bias # Base conv
        K1, B1 = self.conv1x1_3x3.rep_params() # 1x1->3x3 (standard)
        K5, B5 = multiscale(self.conv1x1.weight,3), self.conv1x1.bias # 1x1 -> 3x3

        RK, RB = (K0+K5), (B0+B5)

        if self.with_13:
            RK, RB = RK + K1, RB + B1

        self.rep_conv.weight.data = RK
        self.rep_conv.bias.data = RB

        for para in self.parameters():
            para.detach_()


    def switch_to_deploy(self):

        if self.deploy:
            return
        self.deploy = True

        # Main branches
        K0, B0 = self.rep_conv.weight, self.rep_conv.bias
        K1, B1 = self.conv1x1_3x3.rep_params()
        K2, B2 = self.conv1x1_teo_sbx.rep_params()
        K3, B3 = self.conv1x1_teo_sby.rep_params()

        #------ laplacian pyramid
        K4_lvl1, B4_lvl1 = self.conv1x1_lpl.rep_params()

        # Approximate level 2 & 3 Laplacian Pyramid contributions
        # NOTE: these are approximations of down/conv/up
        K4_lvl2 = 0.25 * K4_lvl1
        B4_lvl2 = 0.25 * B4_lvl1

        K4_lvl3 = 0.0625 * K4_lvl1
        B4_lvl3 = 0.0625 * B4_lvl1

        K5, B5 = multiscale(self.conv1x1.weight,3), self.conv1x1.bias

        # Final collapsed Laplacian Pyramid kernel
        K_LPL = K4_lvl1 + K4_lvl2 + K4_lvl3
        B_LPL = B4_lvl1 + B4_lvl2 + B4_lvl3
        #------
        if self.gv:
            RK, RB = (K0+K2+K3+K_LPL), (B0+B2+B3+B_LPL)
        else:
            RK, RB = (K0+K2+K3+K_LPL+K5), (B0+B2+B3+B_LPL+B5)
            if self.with_13:
                RK, RB = RK + K1, RB + B1
        if self.with_idt:
            device = RK.get_device()
            if device < 0:
                device = None
            K_idt = torch.zeros(self.out_planes, self.out_planes, 3, 3, device=device)
            for i in range(self.out_planes):
                K_idt[i, i, 1, 1] = 1.0
            B_idt = 0.0
            RK, RB = RK + K_idt, RB + B_idt

        # --------------------
        # REPLACE MODULE
        # --------------------

        self.rep_conv = nn.Conv2d(in_channels=self.inp_planes, out_channels=self.out_planes, kernel_size=3, stride=1,
                                      padding=1, bias=True)
        self.rep_conv.weight.data = RK
        self.rep_conv.bias.data = RB

        for para in self.parameters():
            para.detach_()

        # --------------------
        # REMOVE BRANCHES
        # --------------------

        #self.__delattr__('conv3x3')
        self.__delattr__('conv1x1_3x3')
        self.__delattr__('conv1x1')
        self.__delattr__('conv1x1_teo_sbx')
        self.__delattr__('conv1x1_teo_sby')
        self.__delattr__('conv1x1_lpl')


class MFDB_deploy(nn.Module):
    def __init__(self, inp_planes, out_planes):
        super(MFDB_deploy, self).__init__()

        self.rep_conv = nn.Conv2d(in_channels=inp_planes, out_channels=out_planes, kernel_size=3, stride=1,
                                      padding=1, bias=True)

        self.act = nn.PReLU(num_parameters=out_planes)

    def forward(self, x):
        y = self.rep_conv(x)
        y = self.act(y)

        return y


#########################################################################################

# train.py

import os
import torch
from torch.autograd import Variable
from torch.utils.data import DataLoader
import torch.backends.cudnn as cudnn
import time
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
import pandas as pd
import cv2
from pytorch_msssim import ssim, ms_ssim


def train(model, dataloader, criteria, device, optimizer, scheduler, epoch, num_epochs):
    loss_epoch = 0.
    criterion_perceptual = MS_SSIMloss()

    for batch_idx, (LR_img_l, LR_img_r, HR_img_l, name, _, _) in enumerate(dataloader):
    
        optimizer.zero_grad()
        LR_left, LR_right = LR_img_l.to(device).float(), LR_img_r.to(device).float()
        HR_left = HR_img_l.to(device).float()

        SR_left = model(LR_left, LR_right)

        #loss = criteria(SR_left, HR_left)
        loss_char =  criteria(SR_left, HR_left)
        loss_perceptual = criterion_perceptual(SR_left, HR_left)
        # loss_DL = torch.mean(torch.abs(wrapped_SR - LR_right))
        loss = loss_char + 0.1 * loss_perceptual

        # Backpropagation
        loss.backward()
        optimizer.step()
        scheduler.step()

        loss_epoch += loss.item()

        # live progress percentage
        progress = 100.0 * (batch_idx + 1) / len(dataloader)
        print(f"\rEpoch {epoch}/{num_epochs}: {progress:.2f}% completed", end="")

    print()  # new line after finishing one epoch
    loss_epoch /= len(dataloader)
    lr_epoch = scheduler.get_last_lr()[0]
    return loss_epoch, lr_epoch



def validation(model, dataloader, criteria, device):
    loss_epoch = 0.
    psnr_epoch = 0.
    ssim_epoch = 0.
    pred_full_list = []
    name_list_l = []
    name_list_r = []
    name_list = []

    gt_dict = {}
    size_dict = {}

    with torch.no_grad():
        for LR_img_l, LR_img_r, HR_img_l, img_name_l, img_name_r, hr_img_names in dataloader:
            LR_img_l, LR_img_r = LR_img_l.to(device).float(), LR_img_r.to(device).float()
            HR_img_l = HR_img_l.to(device).float()

            HR_pred_patch = model(LR_img_l, LR_img_r)
            HR_pred_patch = torch.clamp(HR_pred_patch, 0, 1)

            loss = criteria(HR_pred_patch, HR_img_l)
            loss_epoch += loss.item()
            pred_full = HR_pred_patch
            HR_full = HR_img_l
            psnr = cal_psnr(pred_full, HR_full)
            ssim_out = ssim(pred_full, HR_full, data_range=1.0, size_average=True)
            psnr_epoch += psnr.item()
            ssim_epoch += ssim_out.item()

            pred_full_list.append(pred_full)
            name_list_l += img_name_l

    loss_epoch /= len(dataloader)
    psnr_epoch /= len(dataloader)  # average per image
    ssim_epoch /= len(dataloader)
    return loss_epoch, psnr_epoch, ssim_epoch, pred_full_list, name_list


save_dir = "your/directory/path/"
SR_rate = 2
pretrained_model = "your/directory/path//best.pt"
# epochs = 5000
epochs = 200
test_every = 1
# batch_size = 32
batch_size = 32   
lr_max = 25e-04
pct_epoch = 30
augment = True
workers = 0
device = 0
div_factor = 50.0
final_div_factor = 0.5


valid_folder = os.path.join(save_dir, 'valid_res')
os.makedirs(valid_folder, exist_ok=True)

device = 'cuda:7'
# device = 'cpu'

model = MTDFN(SR_rate, deploy=False)

# load pretrained model        ########################## uncomment if traing needed a restart
if pretrained_model.endswith('.pt') and os.path.exists(pretrained_model):
        # filter conv4 weights which have different conv channels
        model_dict = model.state_dict()
        #pretrained_dict = torch.load(pretrained_model, map_location='cuda:1')
        pretrained_dict = torch.load(pretrained_model, map_location=device)
        filtered_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict and v.shape == model_dict[k].shape}
        model_dict.update(filtered_dict)
        model.load_state_dict(model_dict)
        print(f"Loaded pretrained model {pretrained_model}" )


model.to(device)

train_dataloader = create_dataloader('train', SR_rate, augment, batch_size,
                                     shuffle=True, num_workers=workers)
batch = next(iter(train_dataloader))


valid_dataloader = create_dataloader('valid', SR_rate, False, 1,
                                     shuffle=True, num_workers=1)

criteria = L1Loss()
optimizer = optim.Adam(model.parameters(), lr=lr_max/div_factor, betas=(0.9, 0.999), eps=1e-08,weight_decay=5e-5)


scheduler = lr_scheduler.OneCycleLR(optimizer, lr_max, epochs=epochs, steps_per_epoch=len(train_dataloader), pct_start=pct_epoch/epochs, anneal_strategy='cos', \
                                        cycle_momentum=False, div_factor=div_factor, final_div_factor=final_div_factor)

epoch_start = 0

txt_path = os.path.join(save_dir, f"result_epoch_{epoch_start}.txt")
best_psnr = 0.
for idx in range(epoch_start, epochs + 1):
    t0 = time.time()
    train_loss_epoch, lr_epoch = train(model, train_dataloader, criteria, device, optimizer, scheduler, idx, epochs)

    if idx % test_every == 0:
        t1 = time.time()
        valid_loss_epoch, psnr_epoch, ssim_epoch, pred_HR_l, img_names_l = validation(model, valid_dataloader, criteria, device)
        t2 = time.time()
        print(f"Epoch: {idx} | lr: {lr_epoch:.5f} | "
              f"training loss: {train_loss_epoch:.5f} | "
              f"validation loss: {valid_loss_epoch:.5f} | "
              f"PSNR: {psnr_epoch:.3f} | SSIM: {ssim_epoch:.3f} | Time: {t2-t0:.1f}")
        with open(txt_path, 'a') as f:
            f.write(f"Epoch: {idx} | lr: {lr_epoch:.5f} | "
                    f"training loss: {train_loss_epoch:.5f} | "
                    f"validation loss: {valid_loss_epoch:.5f} | "
                    f"PSNR: {psnr_epoch:.3f} | SSIM: {ssim_epoch:.3f} | Time: {t2-t0:.1f}\n")

        # Best model saving logic also here
        if psnr_epoch > best_psnr:
            best_psnr = psnr_epoch
            torch.save(model.state_dict(), os.path.join(save_dir, 'best.pt'))
            save_res(pred_HR_l, img_names_l, valid_folder)

        del pred_HR_l



 # visualize the training process
visualize_training(save_dir, epoch_start)
#torch.save(model.state_dict(), os.path.join(save_dir, 'last.pt'))

# ---- NEW: switch to deploy before saving final model ----
print("Switching model to deploy mode for inference...")
model.switch_to_deploy()
torch.save(model.state_dict(), os.path.join(save_dir, 'last_deploy.pt'))

print(f"Training is finished, the best PSNR is {best_psnr:.3f}")
with open(txt_path, 'a') as f:
            f.write(f"Training is finished, the best PSNR is {best_psnr:.3f}")





''' 
## TEST ##
#--------------------- switch to deploy ----------------------------#
import torch
import os


# paths
save_dir = "/path/to/your/directory"
save_dir_1 = "/path/to/your/directory"
input_model_path = os.path.join(save_dir_1, "best.pt")
deploy_model_path = os.path.join(save_dir, "best_deploy.pt")
SR_rate = 2

# Initialize model (same architecture as training)
# device = 'cuda'
# device = 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

model = MTDTFN(scale=SR_rate, deploy = False)
model = model.to(device)

#  Load pretrained weights
state_dict = torch.load(input_model_path, map_location=device)
model.load_state_dict(state_dict)

# Switch to deploy mode
model.switch_to_deploy()

# Save deployable weights
torch.save(model.state_dict(), deploy_model_path)

print(f"Deployable model saved to: {deploy_model_path}")


#--------------- test -----------------#

import os
import argparse
import torch
import time

#from model import XLSR
#from dataset import create_dataloader
#from metric import cal_psnr
#from visualization import save_res


def test(model, dataloader, device, txt_path):
    pred_list_l = []
    # pred_list_r = []
    name_list_l = []
    name_list_r = []
    avg_psnr = 0.
    avg_time = 0.
    with torch.no_grad():
        # print("warm up ...")
        random_input_l = torch.randn(1, 3, 640, 360).to(device)
        random_input_r = torch.randn(1, 3, 640, 360).to(device)

        print("Start the inference ...")
        for LR_img_l, LR_img_r, HR_img_l, img_name, img_name_r, hr_img_names in dataloader:
            LR_img_l, LR_img_r = LR_img_l.to(device).float(), LR_img_r.to(device).float()
            HR_img_l = HR_img_l.to(device).float()


            if device != 'cpu':
                torch.cuda.synchronize()
            t0 = time.perf_counter()
            # print('LR shape = ', LR_img_l.shape,LR_img_r.shape )
            # HR_pred_l = model(LR_img_l, LR_img_r)
            HR_pred_l = infer_patches(model, LR_img_l, LR_img_r, device, patch=256)
            HR_pred_l = torch.clamp(HR_pred_l, 0, 1)
            # HR_pred_l, HR_pred_r = HR_pred[:, :3, :, :], HR_pred[:, 3:, :, :]
            # print('HR_Predictions shape = ', HR_pred_l.shape,HR_pred_r.shape )
            if device != 'cpu':
                torch.cuda.synchronize()
            t1 = time.perf_counter()
            psnr_l = cal_psnr(HR_pred_l, HR_img_l).item()
            # psnr_r = cal_psnr(HR_pred_r, HR_img_r).item()
            psnr = psnr_l
            inference_time = t1 - t0
            print(f"PSRN on {img_name} : {psnr:.3f}, inference time: {1000*inference_time:.2f}ms")
            with open(txt_path, 'a') as f:
                f.write(f"PSRN on {img_name} : {psnr:.3f}, inference time: {1000*inference_time:.2f}ms" + '\n')
            avg_psnr += psnr
            avg_time += inference_time
            # pred_list_l.append(HR_pred_l)
            # Move prediction to CPU
            pred_list_l.append(HR_pred_l.cpu())
            name_list_l += img_name
            # Free GPU memory
            del LR_img_l, LR_img_r, HR_img_l, HR_pred_l
            torch.cuda.empty_cache()

    avg_psnr /= len(test_dataloader)
    avg_time /= len(test_dataloader)
    print(f"Average PSRN: {avg_psnr:.3f}, average inference time: {1000*avg_time:.2f}ms")
    with open(txt_path, 'a') as f:
        f.write(f"Average PSRN: {avg_psnr:.3f}, average inference time: {1000*avg_time:.2f}ms")
    return pred_list_l, name_list_l


save_dir = '/path/to/your/directory'
SR_rate = 2
model_path = '/path/to/your/directory/best_deploy.pt'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# model = MTDTFN(scale=SR_rate, deploy = False)
# model = model.to(device)

# opt = [save_dir, SR_rate, model, device1]

os.makedirs(save_dir, exist_ok=True)

# cuDnn configurations

if device != 'cpu':
        torch.backends.cudnn.benchmark = True
        torch.backends.cudnn.deterministic = True

# txt file to record training process
txt_path = os.path.join(save_dir, 'test_res.txt')
if os.path.exists(txt_path):
        os.remove(txt_path)

    # folder to save the predicted HR image in the validation
test_folder = os.path.join(save_dir, 'test_res')
os.makedirs(test_folder, exist_ok=True)

# device = 'cuda:' + str(device1) if device1 != 'cpu' else 'cpu'
# device = device1
model = MTDTFN(scale=SR_rate, deploy = True)

# load pretrained model
if model_path.endswith('.pt') and os.path.exists(model_path):
        # model.load_state_dict(torch.load(model, map_location=device))
        model.load_state_dict(torch.load(model_path))
else:
        model.load_state_dict(torch.load(os.path.join(save_dir, 'best.pt'), map_location=device))
model.to(device)
model.eval()

test_dataloader = create_dataloader('test', SR_rate, False, batch_size=1, shuffle=False, num_workers=1)
print(len(test_dataloader))
 # evaluate
# pred_HR_l,pred_HR_r, img_names_l,img_names_r, valid_folder = test(model, test_dataloader, device, txt_path)
pred_HR_l, img_names_l = test(model, test_dataloader, device, txt_path)

print("Saving the predicted HR images")
save_res(pred_HR_l, img_names_l, test_folder)
print(f"Testing is done!, predicted HR images are saved in {test_folder}")

'''
